import Express from "express";
import BodyParser from "body-parser";

const Server = new Express();
Server.use(BodyParser.urlencoded({ extended: false }));

const emailListRoute1 = {
  "vuthiphuonghieu17@gmail.com":
    "https://drive.google.com/uc?export=download&id=14kc7tukwgOY2JeCQnzwefxFpUJi88MLJ",
  "anhvannasb@gmail.com":
    "https://drive.google.com/uc?export=download&id=1OpHXLfg-azV0h7IoGBPdSU4GkEYGBRpI",
  "nhmyhanh@gmail.com":
    "https://drive.google.com/uc?export=download&id=1lfZE8ssYBafoxYNNGgfgK0o8quTLc8bK",
  "bachphuonghaiquan@gmail.com":
    "https://drive.google.com/uc?export=download&id=1Y6lcN8UMWqbmB4LIkdNKFrUg6o9S7aVT",
  "binhvinhhuyen@gmail.com":
    "https://drive.google.com/uc?export=download&id=1GWz6V70O9bdBPOuXTnfzHbdaM2JKKuA_",
  "vuthily172@gmail.com":
    "https://drive.google.com/uc?export=download&id=1qL5sbcfW2PKwPfymfKVT6jcftDZCRGwD",
  "letrangia@gmail.com":
    "https://drive.google.com/uc?export=download&id=1hFIvquOsC33-rfOvaPr4dlXVcUd5g49c",
  "quanthaochi@gmail.com":
    "https://drive.google.com/uc?export=download&id=1h62Dd9KJFER7dew-XnAyJ3L6DJrRbhgv",
  "quynhngt@gmail.com":
    "https://drive.google.com/uc?export=download&id=1M9vWNV8eggXh8MklADdwhLULGCTnHpb2",
  "ncaotan@gmail.com":
    "https://drive.google.com/uc?export=download&id=1TIYrQ1RAeoyNGykICJZ0Fd0CCf9vylZB",
  "myhanhta12@gmail.com":
    "https://drive.google.com/uc?export=download&id=12o9WHbrQus_DgSXSdwYtnT9JYFpEm6DN",
  "quynhgiangnhatanh@gmail.com":
    "https://drive.google.com/uc?export=download&id=1uwprAM6j-Uxua07R6RSnDpqwR-tIhkGO",
  "phuongoanh1910@gmail.com":
    "https://drive.google.com/uc?export=download&id=1YJ-2aCSYa5grDrd0dGC5AwDVOLFKjmGX",
  "vuthihienibt2014@gmail.com":
    "https://drive.google.com/uc?export=download&id=10Ra084jhHcfDASqBOdzpW3uVbZmO_WvV",
  "hienle217@gmail.com":
    "https://drive.google.com/uc?export=download&id=1816dWcDTeGI80oxuuf1miSHTVW0XCEQT",
  "vuhuykhanhdang@gmail.com":
    "https://drive.google.com/uc?export=download&id=15ke4UjcSsLA2SEpBo51Lrzx3SolN7t6b",
  "huongtram1984@gmail.com":
    "https://drive.google.com/uc?export=download&id=1HkL6oEdbnWKCfaEod2vmbb0z82FwSuJU",
  "trangviaep@gmail.com":
    "https://drive.google.com/uc?export=download&id=183LhdNu2xPqBChQfmDW2ro28AWDEawFt",
  "lamgiangpleiku@gmail.com":
    "https://drive.google.com/uc?export=download&id=1O9IBPL3ywskh6hSL2R3FRUjXXm7_7vcY",
  "htthuy256@gmail.com":
    "https://drive.google.com/uc?export=download&id=1PPJW6pQIHYGkXiCzwlMHxnHAlBSLu2fj",
  "tranchong1512@gmail.com":
    "https://drive.google.com/uc?export=download&id=1mtvIsofxaAyDiJWEGxN8Mp18SnKEKf23",
  "vandothanh0311@gmail.com":
    "https://drive.google.com/uc?export=download&id=1JextBuWNTElrwp_3KH-8tROdeJeZI5Nb",
  "hienpham.hanam@gmail.com":
    "https://drive.google.com/uc?export=download&id=1xX7Xg8sj6SHdkyJiPHgiASryqj53X3Vz",
  "lizi225@gmail.com":
    "https://drive.google.com/uc?export=download&id=1kUkByUfnrE242J1zK6Jnwfi34xNZBNr4",
  "ltptrinh161@gmail.com":
    "https://drive.google.com/uc?export=download&id=1Sg3DJtyA1_sOuxsA73DNOfnyImifyNZF",
  "nhuquynh521vn@gmail.com":
    "https://drive.google.com/uc?export=download&id=1PjjmJ3b4W2pXtXecme6MBmLc_MNAX9cv",
  "quynhbom2003@gmail.com":
    "https://drive.google.com/uc?export=download&id=1N9ALeCFqhbr63vD_03jY0-wuiQAFC81z",
  "mong2008tiamo@gmail.com":
    "https://drive.google.com/uc?export=download&id=1WpkH2P8nx3VLoDE-qX7P8DabXmXiXsmE",
  "phamthihuongthao051292@gmail.com":
    "https://drive.google.com/uc?export=download&id=1BM3tangBT5mdotvAlMGsJGWpr3Q9xUI7",
  "phamnguyenhoaibao@gmail.com":
    "https://drive.google.com/uc?export=download&id=16jSsggQ-DfOgyl19MD0bHiTPPAlg_qn8",
  "shoes.shop99@gmail.com":
    "https://drive.google.com/uc?export=download&id=14XkL-S0j1ISkDPe1PQEt3v3Je8NAgPlo",
  "hatathi1989@gmail.com":
    "https://drive.google.com/uc?export=download&id=1-AdDH6Dpd8F_SYE9ZGyz2ufNwljUJlMa",
  "ha.techmerit@gmail.com":
    "https://drive.google.com/uc?export=download&id=13R7AwMqzVEZkY95atxR0nqTdQ6FsCI3a",
  "levan2789@gmail.com":
    "https://drive.google.com/uc?export=download&id=1XhWApM5pTMbqhaqS83VimyxLWMluyrH1",
  "drthomgmvd@gmail.com":
    "https://drive.google.com/uc?export=download&id=1QrpM2kZ8ZWlsxzKkHto0lKAmt6qnAIke",
  "fuonghta@gmail.com":
    "https://drive.google.com/uc?export=download&id=1GLYdzWDBeYfLuBSyfHsKASdd45TxTU9y",
  "tuyet.vu0808@gmail.com":
    "https://drive.google.com/uc?export=download&id=1P6r1g2MYR8PO8okl7KLviRZo4M6v0-VL",
  "tonucatien@gmail.com":
    "https://drive.google.com/uc?export=download&id=19g5yu9quaLXgp8_sqSE3LWJ-Po3hjk9d",
  "nguyenthu.etraining@gmail.com":
    "https://drive.google.com/uc?export=download&id=1on0-xxKmeAAckDU5lgZac0GNKmcsOkP0",
  "phanthuydong3012@gmail.com":
    "https://drive.google.com/uc?export=download&id=1CeAEhZKN_8BBi15992SyoaNs4wVK3T9G",
  "tranngatn90@gmail.com":
    "https://drive.google.com/uc?export=download&id=1OatwHbHcjdaFsaNo2rqWrD-BEl-CzJJx",
  "hatrung2222@gmail.com":
    "https://drive.google.com/uc?export=download&id=1DlAv8oU4P07JZeEHuZN6ecFZehF8-YtR",
  "lesam84@gmail.com":
    "https://drive.google.com/uc?export=download&id=1Kbwbfo7RRISvqxlPeBvLUKSOrWLB-Y-i",
  "caohongtuoi@gmail.com":
    "https://drive.google.com/uc?export=download&id=1uBhwj1VB3aswY3LcdwkFa0MFwYIR5rEn",
  "nguyenhoanghoa318@gmail.com":
    "https://drive.google.com/uc?export=download&id=1rI8hVtX2scM_5Gmtyc7B43N9a8PUk6pB",
  "phamtuananhminh2015@gmail.com":
    "https://drive.google.com/uc?export=download&id=1Mi3SzjeUdI1qOBr1fRoQ6LvJO0R5tIV_",
  "thuyhiendin@gmail.com":
    "https://drive.google.com/uc?export=download&id=15e2jo0MivGkkgSgX14-A4vk9lv5yAovo",
  "ntchinh.tc@gmail.com":
    "https://drive.google.com/uc?export=download&id=1qv9nqT3FGWptH0fhvfJDIgH5wS9BAvDZ",
  "haiyenluu@gmail.com":
    "https://drive.google.com/uc?export=download&id=1UTSehZeuubvk2v1gUAEr6Annx1T2IP0C",
  "haiyencmc@gmail.com":
    "https://drive.google.com/uc?export=download&id=1kZzNJKZr7O6aHM-n4NJu5pwxCODPxJYr",
  "daothidiu@gmail.com":
    "https://drive.google.com/uc?export=download&id=17LihtNpBjB_-Tbx-NK4Q_sZxxnuUv5t0",
  "phamthithom219@gmail.com":
    "https://drive.google.com/uc?export=download&id=1XdIsjsSEVzYNUlGZGg800YINZstCUteh",
  "hongtham.nguyen@gmail.com":
    "https://drive.google.com/uc?export=download&id=1v34sZ2rQEpORZ7CULiZ7zv5yVS9ZFGeo",
  "ttnquynh133@gmail.com":
    "https://drive.google.com/uc?export=download&id=1GbTF5vRtSJSD0d6Wzog6qjoALLEaq6_5",
  "ngothanhphuong2788@gmail.com":
    "https://drive.google.com/uc?export=download&id=1KeBuvv5SVYVogbUF2iSG1USdaDb95xV4",
  "lekimhoa.le@gmail.com":
    "https://drive.google.com/uc?export=download&id=1ChySX0RYYsflTWNQCL5U1Ez2GkybOPbI",
  "hadaot@gmail.com":
    "https://drive.google.com/uc?export=download&id=1nlfQ6D6_x61Ps7kqh3CE-GW9YBkL6YWg",
  "minhthu.lion88@gmail.com":
    "https://drive.google.com/uc?export=download&id=1R12eCrbRVxPQ_z6W-Ya9jTk1ebw3miF5",
  "luyennt@vnu.edu.vn":
    "https://drive.google.com/uc?export=download&id=18SXZ3i582-4_ZGjwl1Jspzlq-TTr5yp7",
  "giang.truong.dn@gmail.com":
    "https://drive.google.com/uc?export=download&id=1ZW_Me8lzr5q2krjFo6AS4B7ZFMHMNMzB",
  "uyennt90116@gmail.com":
    "https://drive.google.com/uc?export=download&id=10nMcoHGlN3Y0JMiM-805hjYNy7uU3r-Z",
  "lehuongthabiga@gmail.com":
    "https://drive.google.com/uc?export=download&id=152BleNmmFw5g86WJMpROMDejObvu7PYI",
  "nguyenthiha050981@gmail.com":
    "https://drive.google.com/uc?export=download&id=1CRuPmTb09sBjwML4H9ddped_SWfrOwAa",
  "nguyenlanhuong.yt@gmail.com":
    "https://drive.google.com/uc?export=download&id=1rQ_JdF1sP6xoYzS9bsqq3wFmhWWp0bOT",
  "kieuthuongmon@gmail.com":
    "https://drive.google.com/uc?export=download&id=1khvXhw482zm_SClrnIfef8SrMy7I8ecY",
  "biengoi166@gmail.com":
    "https://drive.google.com/uc?export=download&id=15j_bc9xRIYUmS7zd3cWUImumRR5wRI61",
  "trinhthao87@gmail.com":
    "https://drive.google.com/uc?export=download&id=1Aygpy44TSluzx8hAY9OyTxR2p-U4z5Zk",
  "phananbinh@gmail.com":
    "https://drive.google.com/uc?export=download&id=1-5ou4sGuIZ4cjazHTAU6cwJjNjRLoJvy",
  "phuonglanxn@gmail.com":
    "https://drive.google.com/uc?export=download&id=1Vi3-HILMF0_LXByQ5dbrGWnb-R20PfHO",
  "phanthuy139@gmail.com":
    "https://drive.google.com/uc?export=download&id=1rcYbb-Uk2bhuglWb-SWDhT4sewpsIJOC",
  "xuanhuong0210@gmail.com":
    "https://drive.google.com/uc?export=download&id=1AYB0qD4UtYxQEkMDwtR2NutmJmC0UctB",
  "huyentranganhphap@gmail.com":
    "https://drive.google.com/uc?export=download&id=1BR_8C-ZMjo1nE6zBf8yyzhpBOb6nMbpo",
  "nguyetpostef@gmail.com":
    "https://drive.google.com/uc?export=download&id=1mvVvf8228wDVv9Vv2rLxcB3KmN2ZfnE8",
  "namdldn@gmail.com":
    "https://drive.google.com/uc?export=download&id=1gdAPPeg6oZIpG8MDmhNwBChJd23WM9S7",
  "china.doll2209@gmail.com":
    "https://drive.google.com/uc?export=download&id=1qZRfVyHHhtkrSJeW1d4UxtqF-7I3ZMxv",
  "nhatvinhtn@gmail.com":
    "https://drive.google.com/uc?export=download&id=1ks7Fa-z5o1jEmKGBK5QpzCF3jEZy_Qnc",
  "thupt@hado.vn":
    "https://drive.google.com/uc?export=download&id=1DOoTlsWSXcu3JONRdZqf7vxpsU5sXPfP",
  "thachnguyen87gl@gmail.com":
    "https://drive.google.com/uc?export=download&id=1GnsZha7QPSyMGC3BVqiKZMtAEnSEH7Vf",
  "huongthaodo668@gmail.com":
    "https://drive.google.com/uc?export=download&id=1U-cP1DN6Kb4P76Q-Xwcu5IOIqZ2iU9Qq",
  "suong.liberty@gmail.com":
    "https://drive.google.com/uc?export=download&id=1vIDjBFstqO6jTpUpRo1LDINKu5giyhby",
  "havu.acc@gmail.com":
    "https://drive.google.com/uc?export=download&id=1qYW05WVJBc3W_RVep9GvT9B7Dqu2dJ8Y",
  "honghiep.nguyen83@gmail.com":
    "https://drive.google.com/uc?export=download&id=1FpPEtbELBOkVrymN22ZVLUSdza5wncAK",
  "nguyen.hoa.0710@gmail.com":
    "https://drive.google.com/uc?export=download&id=12sHf4ZuxV6ISJjBr8qvTKNI-WKKCsuYk",
  "huynhhuyentran089@gmail.com":
    "https://drive.google.com/uc?export=download&id=1H_LXLps431hH0KrN-UQ6GAyz-H2JDJtY",
  "nhung8486@gmail.com":
    "https://drive.google.com/uc?export=download&id=1x-vzCJQL5h7Y-TAQJVTws5ELQIcm9Jsi",
  "thuhien.nguyenmw@gmail.com":
    "https://drive.google.com/uc?export=download&id=18f8gY9xG9EiM-0NnX05GMoOW-6OPH-Pp",
  "maiphuong2507@gmail.com":
    "https://drive.google.com/uc?export=download&id=114xVoQ7_jXumjXbSBHPKLql29EM5NYQO",
  "dangha20112011@gmail.com":
    "https://drive.google.com/uc?export=download&id=1w_ul78rmrhhV5kkxtzRzSQqw2BPcQuC0",
  "trinhdieu2607@gmail.com":
    "https://drive.google.com/uc?export=download&id=18j-FGNpH6bE9TAWium4WKNAZJu9kN8NC",
  "ledung.vepf@gmail.com":
    "https://drive.google.com/uc?export=download&id=10JuvwSBIunO575NmUZHw4MG3-A-FLxGB",
  "baoyen.hanetjsc@gmail.com":
    "https://drive.google.com/uc?export=download&id=1vWUCRgww1vLFD8uFiMvL_VHvFalEeh0m",
  "stranger0618@gmail.com":
    "https://drive.google.com/uc?export=download&id=1pvimZ_rQFWxEjI8haYX0HIjEOdRNnDuJ",
  "bachduongvb@gmail.com":
    "https://drive.google.com/uc?export=download&id=1fpv8iqWNQf2F1iBKlxnTimpfvdKL_ucT",
  "ndthuan@misa.com.vn":
    "https://drive.google.com/uc?export=download&id=1PANtiyj4dXoVaPkV3AZK2bnq2_JPDIpK",
  "chuyendt86@gmail.com":
    "https://drive.google.com/uc?export=download&id=1kiQNv-lDg_fpim0HoscBd1XH-z5Dr5zD",
  "trinhthuyvci@gmail.com":
    "https://drive.google.com/uc?export=download&id=174mpHs_k3mNI6TXJN92Lr9JmSpkeTlWf",
  "doannhumai@gmail.com":
    "https://drive.google.com/uc?export=download&id=15PIXA38HJkqnxJdmSEXES7rEL6HxMe8I",
  "thanhchucht89@gmail.com":
    "https://drive.google.com/uc?export=download&id=1vCy5xWXw5repgAtqcsPhCmuudSywFL5n",
};
const emailListRoute2 = {
  "haiyencmc@gmail.com":
    "https://drive.google.com/uc?export=download&id=17Ub4Dmn-biS0Z2FFMYE6S-2dugYiUSOE",
  "phamnguyenhoaibao@gmail.com":
    "https://drive.google.com/uc?export=download&id=1m3VnhqxcRQiqO1FtV2eAXbu-XSzJjMmi",
};

Server.get("/", (req, res) => {
  const emailaddress = req.query.emailaddress;
  res.redirect(301, emailListRoute1[emailaddress]);
});

Server.get("/2", (req, res) => {
  const emailaddress = req.query.emailaddress;
  res.redirect(301, emailListRoute2[emailaddress]);
});

Server.listen(80, () => {
  console.log("Listening at port 80");
});
